### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jsmolic** [wojtekka/6tunnel#11]
Hello, tests are failing  on Gentoo Linux (downstream bug -> https://bugs.gentoo.org/728610) . 
```python
  File "./test.py", line 29
    print "Running with %s" % all_args
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Running with %s" % all_args)?
FAIL test.py (exit status: 1)
```
After tI fixed that up, came
```python
Running with -1  45879 ::1 44199
Traceback (most recent call last):
  File "./test.py", line 116, in <module>
    test(SUCCESS, socket.AF_INET, socket.AF_INET6, '127.0.0.1', '::1')
  File "./test.py", line 58, in test
    client_sock.send(client_sends_first)
TypeError: a bytes-like object is required, not 'str'
```
and after that
```python
Running with -1  39417 ::1 36691
Traceback (most recent call last):
  File "./test.py", line 116, in <module>
    test(SUCCESS, socket.AF_INET, socket.AF_INET6, '127.0.0.1', '::1')
  File "./test.py", line 66, in test
    raise Exception("expected %s yet accept failed" % labels[expect])
Exception: expected success yet accept failed
```
Could you please take a look at these?\
Thanks!

**Comment by wojtekka** [comment]
I moved the test script to Python 3. Are you able to test the `master` branch before I release it?

**Comment by jsmolic** [comment]
Thanks, this works for me now
